### ISSUE TITLE
Need to remove Jquery file.

### ISSUE THREAD

**Issue by championshuttler** [championshuttler/easyFill#17]
As jquery has a lot of code but we dont need it all so ,need to write only js part what we need :)

**Comment by tjeufoolen** [comment]
Working on it

**Comment by tjeufoolen** [comment]
Created a PR, hope I did serve you well :)

**Comment by championshuttler** [comment]
@Athyk did you test the add-ons after changing all this?

**Comment by tjeufoolen** [comment]
![image](https://user-images.githubusercontent.com/12643433/31113523-fc323280-a819-11e7-8ec5-ab82fb6e2036.png)

**Comment by tjeufoolen** [comment]
Yes, seems to work well :)

**Comment by championshuttler** [comment]
do you also test the main work of the add-ons to save the link after clicking the save button and after that pasting somewhere because if that feature of add-ons does not work , console does not show any error :). Kindly check it once again

**Comment by tjeufoolen** [comment]
Works, tested it multiple times. try it yourself :)

**Comment by championshuttler** [comment]
Thanks @Athyk :)
